language: python
python:
- 3.6
install:
- pip install codecov
- pip install -U tox-travis
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davidemoro
  password:
    secure: KhCAMT6/aMi9jr7t98lsgmurjfcEztnmupMuRM5gI+brT+KWa0lGPCo57xqWo76iXW5eWgudwCKKJZXS2tJLiMyHLNIMJuONo0Q19z66Hpg20PJ448TcsLP5b8xU8piSfUKADfYtWce1+xP5OO6vMd0TARMLSCDO2POgXPHnPQuxRm8pROQ4Ovrmfd0Ir/nFRvh783b9wEfw3XPs9L9+1jHuDXMrAlGHkpThTF5QODJS03PnyhLjExyCfQtJsmrxS1lOj6qfCF35yOvt8pKHCrNQAC3o2GkT7BHiuU2UAXyC7iUw2T7zVdXCvaFRbLJishzN//lQFlsqRWGAG3ZUMwWovx33nJggxkG54Lye9pVc6q5t/jIg1Od14ELwweTkX+mI1R8u1NPuBhOhV//OdDYNOku78HxVuO4zy4RCEI0/jlTMFdZ9uaTkHYakSA2zWPrdFwi2TG39YNirKE7jTFWyOagqMOBlWnn8dMEnnZLWnydtMIfSNriUV+8pok6fijIV3wuevsF3MAJf7Q8em0PfSZnsXOA3yCAB06AS/4aIsWZwLbvqnpozRmf+YJ101mea1gCHyXJbJ1FZd1KiBvg+KLyzslYZH0PSpBYrwfDdp6B/VwPEXsSOXPLOc/p4SgfXLREEvTE38ajb5nCxnuHNswNMOCbt/xuvDjzRR3E=
  on:
    tags: true
    repo: davidemoro/play_mqtt
    python: 3.6
